"use client";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "./context/AuthContext";
import TopBar from "./top/TopBar";
import Login from "./components/Login";

import {
  signInWithPopup,
  signOut,
  onAuthStateChanged,
  GoogleAuthProvider,
  getAuth,
} from "firebase/auth";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className=" bg-slate-100">
      <body className={inter.className}>
        <AuthContextProvider>
          <TopBar />
          <NextTopLoader />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
