'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from './context/AuthContext'
import NavBar from '../../components/NavBar'
const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}><AuthContextProvider>
      <NavBar/>
        {children}
      </AuthContextProvider>
        </body>
    </html>
  )
}
